name: Prettier Action

on:
  pull_request_target:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run format

      - name: Commit and Push Prettier Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add .
          git commit -m "chore: format code with Prettier" || echo "No changes to commit"
          git pull --rebase
          git push origin ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secret.PAT }}
